update ci/cd
hcc429/randomcat pull request #2
Opened 2023-07-03 04:06 UTC by yth345

2023-07-07 14:51 UTC, hcc429 commented on .github/workflows/config-gke.yml
> +      - 'kubernetes/**'
這個切的不錯

2023-07-07 14:56 UTC, hcc429 requested changes

2023-07-07 14:56 UTC, hcc429 commented on .github/workflows/config-gke.yml
> +        if: steps.changes.outputs.kubernetes == 'true'
steps.changes.outputs.kubernetes在哪
好像沒有看到qq
這個workflow會被執行代表kubernetes這個資料夾已經有動到了(第7行)

2023-07-07 14:56 UTC, hcc429 commented on server/controllers/dto/like.go
> +	URL    string `json:"url"`
超好笑 謝囉

2023-07-08 05:38 UTC, yth345 commented on .github/workflows/config-gke.yml
> +        if: steps.changes.outputs.kubernetes == 'true'
好好笑 忘了刪了

2023-07-10 04:47 UTC, hcc429 approved these changes

2023-07-10 04:47 UTC, merged